live_config_reload = true

import = [
"~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[font]
normal = { family = "DankMono Nerd Font", style = "Regular" }
size = 16.0

[window]
dynamic_padding = false
opacity = 1.0

[window.padding]
x = 18
y = 16
