[env]
TERM = "xterm-256color"

[font]
normal = { family = "DankMono Nerd Font", style = "Regular" }
size = 16.0

[window]
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 18
y = 16

[general]
live_config_reload = true

import = [
"~/.config/alacritty/catppuccin-macchiato.toml"
]
